name: Run Angular Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Angular unit tests
        run: npm run test -- --watch=false --browsers=ChromeHeadless

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: karma-test-results
          path: test-results/karma-test-results.xml
